### ISSUE TITLE
2.2.9

### ISSUE THREAD

**Issue by hantertill** [ResistancePlatform/resistance-platform-release#12]
child process falure..

**Comment by ghost** [comment]
And what is the solution to this.

I have actually deleted the 3 folders and reinstall… It is taking about 3 hours and I am 25% of my tokens. Either the internet goes slow right now or your server. 

However, what is the solution for this?

Thanks

Juanjo

 

De: hantertill <notifications@github.com> 
Enviado el: 06 April 2020 14:56
Para: ResistancePlatform/resistance-platform-release <resistance-platform-release@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: [ResistancePlatform/resistance-platform-release] 2.2.9 (#12)

 

child process falure..

**Comment by iwuvjhdva** [comment]
Hi @hantertill, could you please provide a screenshot and the logs of your issue? The logs folder can be opened by navigating Settings -> Status Modal -> Logs Folder. Otherwise it is hard to say anything.

**Comment by iwuvjhdva** [comment]
Hi @juaol, I am sorry you are experiencing issues. Can you please tell what is taking so much time? Is it Resistance parameters download or node synchronisation? Thank you!

**Comment by ghost** [comment]
Hi Konstantin
If I i install on top of 2.2.8 then it gives the child node error 1
If you delete old and run from back up , it takes hours to synchronize and mine stops after 3 hours and shows failed 

Happens to a lot of people

Anyway the child error node 1 is associated to the mining address in the settings file . In fact in that address I have 111 euros that I cannot transfer or move or it gives a UTOX cash payment error. I tried to put a new mining addresa and not solve the problem

At least but not last , I have about 70 addresss on my wallet. Every time I make a transaction it creates another address. Either solve this or put a button to hide all close to zero addresses

Thanks
Juanjo

Enviado desde mi iPhone

**Comment by hantertill** [comment]
> Hi @hantertill, could you please provide a screenshot and the logs of your issue? The logs folder can be opened by navigating Settings -> Status Modal -> Logs Folder. Otherwise it is hard to say anything.

Hi, for now use 2.2.8 with new cant enter in settings
![Res error screenshot](https://user-images.githubusercontent.com/63128128/79571900-464ed580-80bc-11ea-8721-e6f2c8547a1a.png)

**Comment by iwuvjhdva** [comment]
Windows binaries were corrupted in 2.2.9, fixed now. Please download and install the updated releast (2.2.9-1):
https://github.com/ResistancePlatform/resistance-platform-release/releases/download/2.2.9/ResistanceWallet-windows-2.2.9-1.exe
Closing the issue.
