### ISSUE TITLE
Can't sell more Res than my Eth balance

### ISSUE THREAD

**Issue by yidakee** [ResistancePlatform/resistance-platform-release#3]
I'm not sure if this is a bug or a feature.

I can't place a Sell order for Res higher than my Eth balance. Here is an example

<img width="555" alt="Screenshot 2019-09-11 at 11 52 25" src="https://user-images.githubusercontent.com/16577836/64693573-75022f00-d48f-11e9-954b-1f9572d3b785.png">

I've confirmed this by sending in more Eth, and I can increase my sell order sizes. If a feature, this seems like a very big limitation for user adoption. For example, miners will certainly not like this at all, and may trigger people flocking to CEX for convenience.

**Comment by yidakee** [comment]
Seems the Advanced Trading tab is inverted. Selling is buying and vice versa.
Lost 40 bucks in Eth due to this "bug" ... Took a hit for Team Resistance :)

**Comment by lukewegryn** [comment]
One of the updates prior to 2.2.7 should have resolved this issue. Closing.
