### ISSUE TITLE
Potential double-bug: One order cancels the other, but persists on the network?

### ISSUE THREAD

**Issue by yidakee** [ResistancePlatform/resistance-platform-release#4]
Seems that you can only have one order on each side. When I create a new one, the previous one disappears. 

Unlisted video on youtube, steps to replicate

[![](http://img.youtube.com/vi/QHsmWurl6b4/0.jpg)](http://www.youtube.com/watch?v=QHsmWurl6b4 "")

Now for the potential "double-bug", I noticed that one of my previous orders got picked up. I am almost certain I had placed orders long after this one got picked up and failed, because it was an order for 1 Res, and I tried multiple subsequent orders. So it seems the offer propagated the network, but if the above is correct (one order cancels the next) - then the cancel order message is propagating very slowly. Just a theory

<img width="633" alt="Screenshot 2019-09-11 at 12 29 32" src="https://user-images.githubusercontent.com/16577836/64694513-b4317f80-d491-11e9-921f-43eb6a75406e.png">
<img width="634" alt="Screenshot 2019-09-11 at 12 30 12" src="https://user-images.githubusercontent.com/16577836/64694515-b4ca1600-d491-11e9-8585-f040cf69c0ac.png">

**Comment by lukewegryn** [comment]
@yidakee, this should have been fixed by a newer release (at least by 2.2.7). If you are still having this issue, let us know. Closing.
